defmodule Loja.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:description, :text)
      add(:technical_description, :text)
      add(:sku, :text)
      add(:brand, :text)
      add(:unit, :text, default: "unidade")
      add(:base_price, :decimal, null: false)
      add(:images, {:array, :text}, default: [])
      add(:active, :boolean, default: true)
      add(:featured, :boolean, default: false)
      add(:tags, {:array, :text}, default: [])
      add(:compatible_ids, {:array, :uuid}, default: [])
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:category_id, :uuid)
    end

    create(unique_index(:products, [:sku], name: "products_unique_sku_index"))

    create(unique_index(:products, [:slug], name: "products_unique_slug_index"))

    create table(:product_variants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:sku, :text, null: false)
      add(:price, :decimal, null: false)
      add(:stock, :bigint, default: 0)
      add(:unit, :text, default: "unidade")
      add(:weight_kg, :decimal)
      add(:attributes, :map, default: %{})
      add(:active, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :product_id,
        references(:products,
          column: :id,
          name: "product_variants_product_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:product_variants, [:sku], name: "product_variants_unique_variant_sku_index")
    )

    create table(:orders, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:contact_name, :text)
      add(:contact_phone, :text)
      add(:contact_email, :text)
      add(:cep, :text)
      add(:shipping_address, :text)
      add(:shipping_method, :text)
      add(:shipping_cost, :decimal, default: "0")
      add(:subtotal, :decimal, null: false)
      add(:total, :decimal, null: false)
      add(:status, :text, default: "pendente")
      add(:status_log, :map, default: %{})
      add(:notes, :text)
      add(:delivered_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:cart_id, :uuid)
    end

    create table(:order_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:quantity, :bigint, null: false)
      add(:unit_price, :decimal, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :order_id,
        references(:orders,
          column: :id,
          name: "order_items_order_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :product_id,
        references(:products,
          column: :id,
          name: "order_items_product_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :variant_id,
        references(:product_variants,
          column: :id,
          name: "order_items_variant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:obra_rules, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:obra_type, :text, null: false)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:prompt_template, :text)
      add(:materials, {:array, :map}, default: [])
      add(:compatibility_rules, {:array, :text}, default: [])
      add(:active, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:products) do
      modify(
        :category_id,
        references(:categories,
          column: :id,
          name: "products_category_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:categories) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:icon, :text)
      add(:position, :bigint, default: 0)
      add(:active, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :parent_id,
        references(:categories,
          column: :id,
          name: "categories_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(unique_index(:categories, [:slug], name: "categories_unique_category_slug_index"))

    create table(:carts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:orders) do
      modify(
        :cart_id,
        references(:carts,
          column: :id,
          name: "orders_cart_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:carts) do
      add(:token, :uuid, null: false)
      add(:status, :text, default: "active")
      add(:expires_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:cart_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:quantity, :bigint, null: false, default: 1)
      add(:unit_price, :decimal, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :cart_id,
        references(:carts,
          column: :id,
          name: "cart_items_cart_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :product_id,
        references(:products,
          column: :id,
          name: "cart_items_product_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :variant_id,
        references(:product_variants,
          column: :id,
          name: "cart_items_variant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:cart_items, "cart_items_cart_id_fkey"))

    drop(constraint(:cart_items, "cart_items_product_id_fkey"))

    drop(constraint(:cart_items, "cart_items_variant_id_fkey"))

    drop(table(:cart_items))

    alter table(:carts) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:expires_at)
      remove(:status)
      remove(:token)
    end

    drop(constraint(:orders, "orders_cart_id_fkey"))

    alter table(:orders) do
      modify(:cart_id, :uuid)
    end

    drop(table(:carts))

    drop_if_exists(
      unique_index(:categories, [:slug], name: "categories_unique_category_slug_index")
    )

    drop(constraint(:categories, "categories_parent_id_fkey"))

    alter table(:categories) do
      remove(:parent_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:active)
      remove(:position)
      remove(:icon)
      remove(:slug)
      remove(:name)
    end

    drop(constraint(:products, "products_category_id_fkey"))

    alter table(:products) do
      modify(:category_id, :uuid)
    end

    drop(table(:categories))

    drop(table(:obra_rules))

    drop(constraint(:order_items, "order_items_order_id_fkey"))

    drop(constraint(:order_items, "order_items_product_id_fkey"))

    drop(constraint(:order_items, "order_items_variant_id_fkey"))

    drop(table(:order_items))

    drop(table(:orders))

    drop(constraint(:product_variants, "product_variants_product_id_fkey"))

    drop_if_exists(
      unique_index(:product_variants, [:sku], name: "product_variants_unique_variant_sku_index")
    )

    drop(table(:product_variants))

    drop_if_exists(unique_index(:products, [:slug], name: "products_unique_slug_index"))

    drop_if_exists(unique_index(:products, [:sku], name: "products_unique_sku_index"))

    drop(table(:products))
  end
end
